[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing for main site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = ["/about-us", "/services", "/recent-projects", "/team", "/success-stories", "/contact"]}

# Country-based domain switching
[[redirects]]
  from = "https://brandgoto.com/*"
  to = "https://brandgoto.ca/:splat"
  status = 301
  force = true
  conditions = {Country = ["CA"]}

[[redirects]]
  from = "https://brandgoto.ca/*"
  to = "https://brandgoto.com/:splat"
  status = 301
  force = true
  conditions = {Country = ["!CA"]}

# Force HTTPS
[[redirects]]
  from = "http://brandgoto.com/*"
  to = "https://brandgoto.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://brandgoto.ca/*"
  to = "https://brandgoto.ca/:splat"
  status = 301
  force = true

# Cache control headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:; font-src 'self' https: data:;"
    Cache-Control = "public, max-age=31536000, immutable" 